# Generated by Django 5.0.4 on 2024-04-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obesity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.FloatField()),
                ('Gender', models.IntegerField(choices=[(1, 'Male'), (0, 'Female')])),
                ('Height', models.FloatField()),
                ('Weight', models.FloatField()),
                ('BMI', models.FloatField()),
            ],
        ),
    ]
